server:
  port: 8080
eureka:  client:    service-url: 
      defaultZone: http://localhost:5060/eureka/eureka
spring:  
  application:
    name: spring-cloud-config-server
  cloud:    config:      server:        git:          uri: https://github.com/QinKuai/JavaEEClass-MSDConfig
          search-paths: .
          username: QinKuai
          password: 