server:
  port: 8080
eureka:  client:    service-url: 
      defaultZone: http://localhost:5060/eureka/eureka
spring:  
  application:
    name: spring-cloud-config-server
  cloud:    config:      server:        git:          uri: https://github.com/QinKuai/JavaEEClass-MSDConfig
          search-paths: .
          username: QinKuai
          password: 
  rabbitmq:    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
management:  endpoints:    web:      exposure:        include: "*"         