spring:
  application:
    name: provider-server
server:  port: 7002
  servlet:    context-path: /provider
eureka:  client:    service-url:      defaultZone: http://localhost:5060/eureka/eureka